- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/build_steps.sh
- .circleci/build_steps.sh
- recipe/meta.yaml
- recipe/yum_requirements.txt
> Rerender, bump version

- recipe/meta.yaml
> Update dependencies - main one is bumping fslpy to 2

- recipe/meta.yaml
> bump to 0.28.2

- recipe/meta.yaml
> tk 8.6.9 causes segfaults on macos

- recipe/meta.yaml
> BF: Entry points wrong way around

- recipe/meta.yaml
> MNT: add freeglut as dependency

- recipe/meta.yaml
> MNT: add freeglut as dependency, bump build, fix entry points

- recipe/meta.yaml
> MNT: Bump to 1.0.1

- recipe/meta.yaml
> MNT: bump version

- recipe/meta.yaml
> MNT: bump to 1.0.7

- recipe/meta.yaml
- recipe/post-link.sh
> MNT: Work around issue with FSL wrapper script creation on macOS

- recipe/meta.yaml
> MNT: Move sphinx/mock into build deps

- recipe/meta.yaml
> REL: 1.4.4

- recipe/meta.yaml
> MNT: Bump fslpy/widgets/mpl

- recipe/meta.yaml
> REL: 1.8.2

- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
> REL: 1.10.2

- recipe/meta.yaml
> REL: Bump to 1.12.2

- recipe/meta.yaml
> REL: bump to 1.12.3

- recipe/meta.yaml
> Unpin wxpython; new build was out quicker than expected

- recipe/meta.yaml
> MNT: bump to 1.12.6

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .gitignore
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- build-locally.py
- recipe/meta.yaml
> REL: 1.14.1
